/**
 * processMap.js
 * 将 texture/Well.png 二值图转换为游戏地图数据
 * 
 * 图片约定：
 *   黑色 (dark) = 岩石/洞穴壁 → 1
 *   白色 (light) = 水道/通道  → 0
 *   灰色过渡区 → 根据亮度阈值判断
 * 
 * 运行方式：
 *   node scripts/processMap.js
 * 
 * 依赖：jimp（需先安装：npm install jimp --save-dev）
 */

const Jimp = require('jimp');
const fs = require('fs');
const path = require('path');

// ===== 配置（与 config.ts 保持一致）=====
const TARGET_COLS = 80;   // CONFIG.cols
const TARGET_ROWS = 150;  // CONFIG.rows

// 亮度阈值：高于此值视为水道(0)，低于此值视为岩石(1)
// 范围 0~255，128 是中间值，可根据图片效果调整
const BRIGHTNESS_THRESHOLD = 128;

// 输入/输出路径
const INPUT_IMAGE = path.join(__dirname, '../texture/Well.png');
const OUTPUT_TS   = path.join(__dirname, '../src/world/mapData.ts');

// ===== 主流程 =====
async function processMap() {
    console.log(`读取图片: ${INPUT_IMAGE}`);
    
    let img;
    try {
        img = await Jimp.read(INPUT_IMAGE);
    } catch (e) {
        console.error('读取图片失败:', e.message);
        process.exit(1);
    }

    const origW = img.getWidth();
    const origH = img.getHeight();
    console.log(`原始尺寸: ${origW} x ${origH}`);

    // 转为灰度，方便亮度判断
    img.grayscale();

    // 缩放到目标尺寸（cols x rows）
    // Jimp.RESIZE_BILINEAR 保留过渡灰色，便于阈值处理
    img.resize(TARGET_COLS, TARGET_ROWS, Jimp.RESIZE_BILINEAR);
    console.log(`缩放到: ${TARGET_COLS} x ${TARGET_ROWS}`);

    // 采样生成地图矩阵
    const mapData = [];
    let wallCount = 0;
    let openCount = 0;

    for (let r = 0; r < TARGET_ROWS; r++) {
        mapData[r] = [];
        for (let c = 0; c < TARGET_COLS; c++) {
            const rgba = Jimp.intToRGBA(img.getPixelColor(c, r));
            // 灰度图 R=G=B，取 R 通道作为亮度
            const brightness = rgba.r;
            // 亮度高 → 白色 → 水道 → 0
            // 亮度低 → 黑色 → 岩石 → 1
            const cell = brightness >= BRIGHTNESS_THRESHOLD ? 0 : 1;
            mapData[r][c] = cell;
            if (cell === 1) wallCount++;
            else openCount++;
        }
    }

    console.log(`岩石格子: ${wallCount}，水道格子: ${openCount}`);
    console.log(`水道占比: ${(openCount / (TARGET_ROWS * TARGET_COLS) * 100).toFixed(1)}%`);

    // 序列化为紧凑格式（每行一个数组，方便阅读）
    const rows = mapData.map(row => `  [${row.join(',')}]`).join(',\n');
    const tsContent = `// Auto-generated by scripts/processMap.js
// Source: texture/Well.png  (${TARGET_COLS}x${TARGET_ROWS})
// Black(rock)=1, White(water)=0
// DO NOT EDIT MANUALLY

export const CAVE_MAP_DATA: number[][] = [
${rows}
];
`;

    fs.writeFileSync(OUTPUT_TS, tsContent, 'utf-8');
    console.log(`\n✅ 地图数据已写入: ${OUTPUT_TS}`);
    console.log('下一步：在 map.ts 中导入并使用 CAVE_MAP_DATA');
}

processMap().catch(err => {
    console.error('处理失败:', err);
    process.exit(1);
});
