"""
processMap.py
将 texture/Well.png 二值图转换为游戏地图数据

图片约定：
  黑色 (dark)  = 岩石/洞穴壁 → 1
  白色 (light) = 水道/通道   → 0
  灰色过渡区   → 根据亮度阈值判断

图片方向：原图为横向(1344x768)，洞穴从左到右延伸
  → 旋转90°逆时针后变为竖向，洞穴从上到下延伸，匹配游戏竖向地图

运行方式：
  python3 scripts/processMap.py

依赖：Pillow（pip3 install Pillow）
"""

import os
from PIL import Image

# ===== 配置（与 config.ts 保持一致）=====
TARGET_COLS = 80    # CONFIG.cols
TARGET_ROWS = 150   # CONFIG.rows

# 亮度阈值：高于此值视为水道(0)，低于此值视为岩石(1)
# 范围 0~255，128 是中间值
BRIGHTNESS_THRESHOLD = 128

# 旋转方向：
#   'ccw'  = 逆时针90°
#   'cw'   = 顺时针90°
#   'none' = 不旋转（图片方向本身已正确）
ROTATE = 'none'

# 路径
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
INPUT_IMAGE = os.path.join(SCRIPT_DIR, '../texture/Well.png')
OUTPUT_TS   = os.path.join(SCRIPT_DIR, '../src/world/mapData.ts')

def auto_crop(img: Image.Image, threshold: int = 128) -> Image.Image:
    """裁剪掉四周全黑的边框，保留有效内容区域"""
    pixels = img.load()
    w, h = img.size

    # 找到有白色像素的边界
    left, right, top, bottom = w, 0, h, 0
    for y in range(h):
        for x in range(w):
            if pixels[x, y] >= threshold:
                if x < left:   left   = x
                if x > right:  right  = x
                if y < top:    top    = y
                if y > bottom: bottom = y

    if right <= left or bottom <= top:
        print("  警告：未找到有效白色区域，跳过裁剪")
        return img

    # 加一点边距
    pad = 5
    left   = max(0, left   - pad)
    top    = max(0, top    - pad)
    right  = min(w, right  + pad)
    bottom = min(h, bottom + pad)

    print(f"  裁剪区域: ({left},{top}) → ({right},{bottom})，原尺寸: {w}x{h}")
    return img.crop((left, top, right, bottom))

def process_map():
    print(f"读取图片: {INPUT_IMAGE}")
    
    img = Image.open(INPUT_IMAGE)
    orig_w, orig_h = img.size
    print(f"原始尺寸: {orig_w} x {orig_h}，模式: {img.mode}")

    # 转为灰度
    img = img.convert('L')

    # 旋转（让洞穴方向变为竖向）
    if ROTATE == 'ccw':
        img = img.rotate(90, expand=True)
        print(f"逆时针旋转90°后尺寸: {img.size[0]} x {img.size[1]}")
    elif ROTATE == 'cw':
        img = img.rotate(-90, expand=True)
        print(f"顺时针旋转90°后尺寸: {img.size[0]} x {img.size[1]}")

    # 自动裁剪黑边
    print("自动裁剪黑边...")
    img = auto_crop(img, BRIGHTNESS_THRESHOLD)
    print(f"裁剪后尺寸: {img.size[0]} x {img.size[1]}")

    # 缩放到目标尺寸（cols x rows）
    img = img.resize((TARGET_COLS, TARGET_ROWS), Image.LANCZOS)
    print(f"缩放到: {TARGET_COLS} x {TARGET_ROWS}")

    pixels = img.load()

    map_data = []
    wall_count = 0
    open_count = 0

    for r in range(TARGET_ROWS):
        row = []
        for c in range(TARGET_COLS):
            brightness = pixels[c, r]  # 灰度值 0~255
            # 亮度高 → 白色 → 水道 → 0
            # 亮度低 → 黑色 → 岩石 → 1
            cell = 0 if brightness >= BRIGHTNESS_THRESHOLD else 1
            row.append(cell)
            if cell == 1:
                wall_count += 1
            else:
                open_count += 1
        map_data.append(row)

    total = TARGET_ROWS * TARGET_COLS
    print(f"\n岩石格子: {wall_count}，水道格子: {open_count}")
    print(f"水道占比: {open_count / total * 100:.1f}%")

    # 序列化为紧凑格式（每行一个数组）
    rows_str = ',\n'.join(
        '  [' + ','.join(str(v) for v in row) + ']'
        for row in map_data
    )

    ts_content = f"""// Auto-generated by scripts/processMap.py
// Source: texture/Well.png  ({TARGET_COLS}x{TARGET_ROWS})
// Black(rock)=1, White(water)=0
// DO NOT EDIT MANUALLY

export const CAVE_MAP_DATA: number[][] = [
{rows_str}
];
"""

    with open(OUTPUT_TS, 'w', encoding='utf-8') as f:
        f.write(ts_content)

    print(f"\n✅ 地图数据已写入: {OUTPUT_TS}")

if __name__ == '__main__':
    process_map()
